package com.company.gui;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class addStudent extends javax.swing.JFrame {

    public  static Connection con;
    public static Statement stat;
    public static int id;
    public static String St_fn;
    public static String St_mn;
    public static String St_ln;
    public static ArrayList <String> oldCourse = new ArrayList<>();
    static {
        try {
            con = Connection1.getCon();
            stat = con.createStatement();
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"SQL connection not found","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    public addStudent() {
        initComponents();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(d.width/2-this.getSize().width/2,d.height/2 - this.getSize().height/2);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        middleName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        instructor1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        instructor2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        instructor3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        instructor4 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        instructor5 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        instructor6 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        instructor7 = new javax.swing.JTextField();
        Course1 = new javax.swing.JComboBox<>();
        Course2 = new javax.swing.JComboBox<>();
        Course3 = new javax.swing.JComboBox<>();
        Course4 = new javax.swing.JComboBox<>();
        Course5 = new javax.swing.JComboBox<>();
        Course6 = new javax.swing.JComboBox<>();
        Course7 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("firstname");

        jLabel2.setText("midlename");

        jLabel3.setText("lastname");

        jLabel4.setFont(new java.awt.Font("Times New Roman", Font.BOLD, 14)); // NOI18N
        jLabel4.setText("course1");

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });

        jLabel11.setText("add student");

        jLabel12.setText("password");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (SQLException throwables) {
                    throwables.printStackTrace();
                }
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setText("course code");

        jLabel14.setText("instructor id");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("course 2");

        jLabel16.setText("course code");

        jLabel17.setText("instructor id");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("course 3");

        jLabel19.setText("course code");

        jLabel20.setText("instructor id");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("course 4");

        jLabel22.setText("course code");

        jLabel23.setText("instructor id");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("course 5");

        jLabel25.setText("course code");

        jLabel26.setText("instructor id");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setText("course 6");

        jLabel28.setText("course code");

        jLabel29.setText("instructor id");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("course 7");

        jLabel31.setText("course code");

        jLabel32.setText("instructor id");

      /*  Course1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course1ActionPerformed(evt);
            }
        });

        Course2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course2ActionPerformed(evt);
            }
        });

        Course3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course3ActionPerformed(evt);
            }
        });

        Course4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course4ActionPerformed(evt);
            }
        });

        Course5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course5ActionPerformed(evt);
            }
        });

        Course6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course6ActionPerformed(evt);
            }
        });

        Course7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course7ActionPerformed(evt);
            }
        });*/

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jLabel1)
                                                                .addComponent(jLabel2)
                                                                .addComponent(jLabel3))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(7, 7, 7)
                                                                .addComponent(jLabel12)))
                                                .addGap(110, 110, 110)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(middleName, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                                                .addComponent(firstname)
                                                                .addComponent(lastName))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(150, 150, 150)
                                                .addComponent(jLabel11))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                                                .addComponent(jLabel25)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(Course5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(36, 36, 36)
                                                                .addComponent(jLabel26)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(instructor5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                                                .addComponent(jLabel13)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(Course1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(36, 36, 36)
                                                                .addComponent(jLabel14)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(instructor1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                                                .addComponent(jLabel28)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(Course6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(36, 36, 36)
                                                                .addComponent(jLabel29)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(instructor6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                                                .addComponent(jLabel16)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(Course2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(36, 36, 36)
                                                                .addComponent(jLabel17)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(instructor2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                                                .addComponent(jLabel19)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(Course3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(36, 36, 36)
                                                                .addComponent(jLabel20)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(instructor3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                                                .addComponent(jLabel22)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(Course4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(36, 36, 36)
                                                                .addComponent(jLabel23)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(instructor4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel31)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(Course7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(jButton1)
                                                                                .addGap(25, 25, 25)))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(20, 20, 20)
                                                                                .addComponent(jLabel32)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(instructor7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(36, 36, 36)
                                                                                .addComponent(jButton2)))))))
                                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(middleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel3))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(instructor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Course1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17)
                                        .addComponent(instructor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Course2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel20)
                                        .addComponent(instructor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Course3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel23)
                                        .addComponent(instructor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Course4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel26)
                                        .addComponent(instructor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Course5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel29)
                                        .addComponent(instructor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Course6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel31)
                                        .addComponent(jLabel32)
                                        .addComponent(instructor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Course7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>





   /* private void Course1ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (!Course1.getSelectedItem().toString().equals("null")) {

                Course2.removeItem(Course1.getSelectedItem());

                Course3.removeItem(Course1.getSelectedItem());

                Course4.removeItem(Course1.getSelectedItem());

                Course5.removeItem(Course1.getSelectedItem());

                Course6.removeItem(Course1.getSelectedItem());

                Course7.removeItem(Course1.getSelectedItem());
            }
        }catch (RuntimeException e) {
            System.out.println("oops");
            e.printStackTrace();
        }
    }

    private void Course2ActionPerformed (ActionEvent evt) {
        try {
            if (!Course2.getSelectedItem().toString().equals("null")) {

                Course1.removeItem(Course2.getSelectedItem());

                Course3.removeItem(Course2.getSelectedItem());

                Course4.removeItem(Course2.getSelectedItem());

                Course5.removeItem(Course2.getSelectedItem());

                Course6.removeItem(Course2.getSelectedItem());

                Course7.removeItem(Course2.getSelectedItem());
            }
        }catch (RuntimeException e) {
            System.out.println("oops");
            e.printStackTrace();
        }
    }


    private void Course3ActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            if (!Course3.getSelectedItem().toString().equals("null")) {

                Course1.removeItem(Course3.getSelectedItem());

                Course2.removeItem(Course3.getSelectedItem());

                Course4.removeItem(Course3.getSelectedItem());

                Course5.removeItem(Course3.getSelectedItem());

                Course6.removeItem(Course3.getSelectedItem());

                Course7.removeItem(Course3.getSelectedItem());
            }
        }catch (RuntimeException e) {
            System.out.println("oops");
            e.printStackTrace();
        }
    }

    private void Course4ActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            if (!Course4.getSelectedItem().toString().equals("null")) {

                Course1.removeItem(Course4.getSelectedItem());

                Course2.removeItem(Course4.getSelectedItem());

                Course3.removeItem(Course4.getSelectedIndex());

                Course5.removeItem(Course4.getSelectedItem());

                Course6.removeItem(Course4.getSelectedItem());

                Course7.removeItem(Course4.getSelectedItem());
            }
        }catch (RuntimeException e) {
            System.out.println("oops");
            e.printStackTrace();
        }

    }

    private void Course5ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (!Course5.getSelectedItem().toString().equals("null")) {

                Course1.removeItem(Course5.getSelectedItem());

                Course2.removeItem(Course5.getSelectedItem());

                Course3.removeItem(Course4.getSelectedItem());

                Course4.removeItem(Course4.getSelectedItem());

                Course6.removeItem(Course4.getSelectedItem());

                Course7.removeItem(Course4.getSelectedItem());
            }
        }catch (RuntimeException e) {
            System.out.println("oops");
            e.printStackTrace();
        }
    }

    private void Course6ActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            if (!Course6.getSelectedItem().toString().equals("null")) {

                Course1.removeItem(Course6.getSelectedItem());

                Course2.removeItem(Course6.getSelectedItem());

                Course3.removeItem(Course6.getSelectedItem());

                Course4.removeItem(Course6.getSelectedItem());

                Course5.removeItem(Course6.getSelectedItem());

                Course7.removeItem(Course6.getSelectedItem());
            }
        }catch (RuntimeException e) {
            System.out.println("oops");
            e.printStackTrace();
        }
    }

    private void Course7ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (!Course6.getSelectedItem().toString().equals("null")) {

                Course1.removeItem(Course7.getSelectedItem());

                Course2.removeItem(Course7.getSelectedItem());

                Course3.removeItem(Course7.getSelectedItem());

                Course4.removeItem(Course7.getSelectedItem());

                Course5.removeItem(Course7.getSelectedItem());

                Course6.removeItem(Course7.getSelectedItem());
            }
        }catch (RuntimeException e) {
            System.out.println("oops");
            e.printStackTrace();
        }
    }*/

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        admin m = new admin();
        m.setVisible(true);
        dispose();
    }
    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        String sql;
        String fname=firstname.getText();
        String mname= middleName.getText();
        String lname= lastName.getText();
        String pass=password.getText();
        St_fn = fname;
        St_mn = mname;
        St_ln = lname;
        String course1=(String) Course1.getSelectedItem();
        String course2=(String) Course2.getSelectedItem();
        String course3=(String) Course3.getSelectedItem();
        String course4=(String) Course4.getSelectedItem();
        String course5=(String) Course5.getSelectedItem();
        String course6=(String) Course6.getSelectedItem();
        String course7=(String) Course7.getSelectedItem();
        List <String> d = new ArrayList<>();
        d.add(course1);
        d.add(course2);
        d.add(course3);
        d.add(course4);
        d.add(course5);
        d.add(course6);
        d.add(course7);
        String instructor_id1=instructor1.getText();
        String instructor_id2=instructor2.getText();
        String instructor_id3=instructor3.getText();
        String instructor_id4=instructor4.getText();
        String instructor_id5=instructor5.getText();
        String instructor_id6=instructor6.getText();
        String instructor_id7=instructor7.getText();
        if(isDifferent(d))
            JOptionPane.showMessageDialog(null, "Same Course selected twice","Failed",JOptionPane.INFORMATION_MESSAGE);

        if(!notAllNull(d))
            JOptionPane.showMessageDialog(null, "Must three courses get selected","Failed",JOptionPane.INFORMATION_MESSAGE);
        else {
            sql = "insert into student(student_Fname,student_Mname,student_lname,student_gpa,course1,course2,course3,course4,course5,course6,course7) values ('" + fname
                    + "','"
                    + mname//First Name
                    + "','"
                    + lname//last Name
                    + "',0,'"//GPA
                    + course1
                    + "','"
                    + course2
                    + "','"
                    + course3
                    + "','"
                    + course4
                    + "','"
                    + course5
                    + "','"
                    + course6
                    + "','"
                    + course7
                    + "')";
            int result = stat.executeUpdate(sql);
            sql = "select student_ID from student where student_Fname = '" + fname + "' and student_Mname = '" + mname + "' and student_lname = '" + lname + "' ";//Insert into student table
            ResultSet ra = stat.executeQuery(sql);
            ra.next();

            id = ra.getInt("student_ID");
            sql = "insert into allPassword (id,pass,person) values (" + id + ",'" + pass + "','student')";//Insert Into Password table
            stat.executeUpdate(sql);
            if (!course1.equals("null")) {
                sql = "insert into " + course1 + " (studentId ,instructorID) values (" + id + "," + instructor_id1 + ")";
                stat.executeUpdate(sql);
            }
            if (!course2.equals("null")) {
                sql = "insert into " + course2 + " (studentId ,instructorID) values ('" + id + "'," + instructor_id2 + ")";
                stat.executeUpdate(sql);
            }
            if (!course3.equals("null")) {
                sql = "insert into " + course3 + " (studentId ,instructorID) values (" + id + "," + instructor_id3 + ")";
                stat.executeUpdate(sql);
            }
            if (!course4.equals("null")) {
                sql = "insert into " + course4 + " (studentId ,instructorID) values (" + id + "," + instructor_id4 + ")";
                stat.executeUpdate(sql);
            }
            if (!course5.equals("null")) {
                sql = "insert into " + course5 + " (studentId ,instructorID) values (" + id + "," + instructor_id5 + ")";
                stat.executeUpdate(sql);
            }
            if (!course6.equals("null")) {
                sql = "insert into " + course6 + " (studentId ,instructorID) values (" + id + "," + instructor_id6 + ")";
                stat.executeUpdate(sql);
            }
            if (!course7.equals("null")) {
                sql = "insert into " + course7 + " (studentId ,instructorID) values (" + id + "," + instructor_id7 + ")";
                stat.executeUpdate(sql);
            }
            if (result == 1) {
                JOptionPane.showMessageDialog(null, "Student account has been created successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        try {
            String sql;
            System.out.println();
            sql = "select courseCode from course";
            ResultSet ra = stat.executeQuery(sql);
            ArrayList <String> course = new ArrayList<>();
            course.add("null");
            while (ra.next()) {
                course.add(ra.getString("courseCode"));
                oldCourse.add(ra.getString("courseCode"));
            }

            DefaultComboBoxModel mod = new DefaultComboBoxModel(course.toArray());
            Course1.setModel(mod);

            // course.remove(mod.getSelectedItem());
            DefaultComboBoxModel mod2 = new DefaultComboBoxModel(course.toArray());
            Course2.setModel(mod2);

            //    course.remove(mod2.getSelectedItem());
            DefaultComboBoxModel mod3= new DefaultComboBoxModel(course.toArray());
            Course3.setModel(mod3);

            //    course.remove(mod3.getSelectedItem());
            DefaultComboBoxModel mod4 = new DefaultComboBoxModel(course.toArray());
            Course4.setModel(mod4);

            //   course.remove(mod4.getSelectedItem());
            DefaultComboBoxModel mod5 = new DefaultComboBoxModel(course.toArray());
            Course5.setModel(mod5);

            //    course.remove(mod5.getSelectedItem());
            DefaultComboBoxModel mod6 = new DefaultComboBoxModel(course.toArray());
            Course6.setModel(mod6);

            //   course.remove(mod6.getSelectedItem());
            DefaultComboBoxModel mod7 = new DefaultComboBoxModel(course.toArray());
            Course7.setModel(mod7);
        }
        catch (SQLException e) {
            System.out.println("oops");
            e.printStackTrace();
        }
    }

    boolean isDifferent(List courses){
        for (int i = 0; i < courses.size(); i++) {
            for (int j = 0; j < courses.size(); j++) {
                if(courses.get(i).equals(courses.get(j)) && (i != j) && !courses.get(i).equals("null") && !courses.get(j).equals("null"))
                    return true;
            }
        }
        return false;
    }

    boolean notAllNull(List courses){
        int count  = 0;
        for (int i = 0; i < courses.size(); i++) {
            if(courses.get(i).equals("null"))
                count++;
        }
        if (count > 4)
            return false;
        else
            return true;
    }

    public static void main(String[] args) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudent().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
  //  private moddedCombobox<String> Course0;
    private javax.swing.JComboBox<String> Course1;
    private javax.swing.JComboBox<String> Course2;
    private javax.swing.JComboBox<String> Course3;
    private javax.swing.JComboBox<String> Course4;
    private javax.swing.JComboBox<String> Course5;
    private javax.swing.JComboBox<String> Course6;
    private javax.swing.JComboBox<String> Course7;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField instructor1;
    private javax.swing.JTextField instructor2;
    private javax.swing.JTextField instructor3;
    private javax.swing.JTextField instructor4;
    private javax.swing.JTextField instructor5;
    private javax.swing.JTextField instructor6;
    private javax.swing.JTextField instructor7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField middleName;
    private javax.swing.JPasswordField password;
    // End of variables declaration
}
